todo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('todo/register/', views.sign_up, name='register'),
    path('/todo/logout/', views.logout, name='logout'),
    path('todolists/create', views.create_todo_list, name='create_todo_list'),
    path('todolists/<str:todolist_id>/todolistitem/create', views.create_todo_list_item, name='create_todo_list_item'),
    path('todolists/<str:id>/update', views.update_todo_list, name='update_todo_list'),
    path('todolists/<str:id>/delete', views.delete_todo_list, name='delete_todo_list'),
    path('todolists/<str:todolist_id>/items', views.todo_list_items, name='todo_list_items'),
    path('todolistitem/<str:id>/delete', views.delete_todo_list_item, name='delete_todo_list_item'),
    path('todolistitem/<str:id>/update', views.update_todo_list_item, name='update_todo_list_item'),
    path('todolistitem/<str:id>/change_status', views.mark_todo_list_item, name='mark_todo_list_item'),
    path('todolistitem/<str:id>/detail', views.detail, name='detail'),
]

todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('todo/', include('django.contrib.auth.urls')),
]

todo/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime
from django.db.models.deletion import CASCADE

class ToDoList(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    name = models.CharField(max_length=32)
    create_date = models.DateTimeField(default=datetime.now(), blank=True)

    def str(self):
        return self.name


class ToDoListItem(models.Model):
    class ToDoListItemStatus(models.TextChoices):
        UNCOMPLETED = 'UNCOMPLETED'
        COMPLETED = 'COMPLETED'
        EXPIRED = 'EXPIRED'

    todolist = models.ForeignKey(ToDoList, on_delete=CASCADE)
    name = models.CharField(max_length=32)
    description = models.TextField()
    create_date = models.DateTimeField(default=datetime.now(), blank=True)
    deadline = models.DateTimeField()
    status = models.TextField(choices=ToDoListItemStatus.choices, default=ToDoListItemStatus.UNCOMPLETED)

    def str(self):
        return self.name

todo/forms/ToDoListForm.py
from django import forms
from todo.models import ToDoList, ToDoListItem


class ToDoListForm(forms.ModelForm):
    class Meta:
        model = ToDoList
        exclude = ['user', 'create_date']


class ToDoListItemForm(forms.ModelForm):
    deadline = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'placeholder': 'Deadline'}))
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ' Item Name'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': ' Description '}))

    class Meta:
        model = ToDoListItem
        exclude = ['todolist', 'create_date', 'status']

todo/views.py
from todo.forms.ToDoListForm import ToDoListForm, ToDoListItemForm
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from .models import ToDoList, ToDoListItem


def sign_up(request):
    context = {}
    form = UserCreationForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            user = form.save()
            login(request, user)
            return render(request, 'todo/index.html')
    context['form'] = form
    return render(request, 'registration/register.html', context)


def logout_view(request):
    logout(request)
    return render(request, 'todo/login.html')


@login_required
def index(request):
    if request.user.is_authenticated:
        data = ToDoList.objects.filter(user_id=request.user.id)
        return render(request, 'todo/index.html', {'list': data})


@login_required
def create_todo_list(request):
    form = ToDoListForm()
    if request.method == 'POST':
        list = ToDoList(user=request.user)
        form = ToDoListForm(request.POST, instance=list)
        if form.is_valid():
            form.save()
            return redirect(index)
    return render(request, 'todo/create_list.html', {'create_todo_list': form})


@login_required
def create_todo_list_item(request, todolist_id):
    form = ToDoListItemForm()
    if request.method == 'POST':
        todo_list = ToDoList.objects.get(id=todolist_id)
        item = ToDoListItem(todolist=todo_list)
        form = ToDoListItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('todo_list_items', todolist_id)
    return render(request, 'todo/create_list_item.html', {'create_todo_list_item': form})


@login_required
def update_todo_list(request, id):
    form = ToDoList.objects.get(id=id)
    data = ToDoListForm(instance=form)
    if request.method == 'POST':
        list = ToDoListForm(request.POST, instance=form)
        if list.is_valid():
            list.save()
            return redirect(index)

    return render(request, 'todo/update_list.html', {'update_todo_list': data})


@login_required
def update_todo_list_item(request, id):
    item = ToDoListItem.objects.get(id=id)
    form = ToDoListItemForm(instance=item)
    if request.method == 'POST':
        form = ToDoListItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('todo_list_items', item.todolist.id)
    return render(request, 'todo/update_list_item.html', {'update_todo_list_item': form})


@login_required
def delete_todo_list(request, id):
    todo_list = ToDoList.objects.get(id=id)
    todo_list.delete()
    return redirect(index)


@login_required
def delete_todo_list_item(request, id):
    todo_list_item = ToDoListItem.objects.get(id=id)
    todolist_id = todo_list_item.todolist.id
    todo_list_item.delete()
    return redirect('todo_list_items', todolist_id)


@login_required
def todo_list_items(request, todolist_id):
    todo_list_items = ToDoListItem.objects.filter(todolist_id=todolist_id)
    todo_list = ToDoList.objects.get(id=todolist_id)
    if todo_list_items.count() == 0:
        return redirect(index)
    return render(request, 'todo/index.html', {'todo_list_items': todo_list_items, 'todo_list': todo_list})


def mark_todo_list_item(request, id):
    item = ToDoListItem.objects.get(id=id)
    if item.status == ToDoListItem.ToDoListItemStatus.UNCOMPLETED:
        item.status = ToDoListItem.ToDoListItemStatus.COMPLETED
    elif item.status == ToDoListItem.ToDoListItemStatus.COMPLETED:
        item.status = ToDoListItem.ToDoListItemStatus.UNCOMPLETED
    item.save()
    return redirect('todo_list_items', item.todolist.id)


def detail(request, id):
    todo_list_item = ToDoListItem.objects.get(id=id)
    return render(request, 'todo/detail.html', {'todo_list_item': todo_list_item})

templates/todo/create_list.html
{% extends 'todo/index.html' %}
{% block content %}
    <form method='post'>
        <h3> Create ToDoList </h3>
        {% csrf_token %}
        {{ create_todo_list }}
        <button type='submit' method='post'>Create</button>
    </form>
{% endblock content %}

templates/todo/create_list_item.html
{% extends 'todo/index.html' %}
{% block content %}
    <form method='post'>
        <h3> Create ToDoList Item </h3>
        {% csrf_token %}
        {% for item in create_todo_list_item %} <br>
            <label for='post'>{{ item }}</label>
        {% endfor %}
        <br>
        <button type='submit' method='post'>Create</button>
    </form>
    <script>
        $('#id_deadline').before('<span> Deadline : </span>')
    </script>
{% endblock content %}

templates/todo/detail.html
{% extends 'todo/index.html' %}
{% block content %}
<table class='item-table col-md-12' id='myTable'>
    <thead>
        <tr>
            <th><a style="cursor: pointer">Name</a>
            </th>
            <th><a style="cursor: pointer"><u>Created Date</u></th>
            </a>
            <th><a style="cursor: pointer"><u>Deadline</u></th>
            </a>
            <th><a style="cursor: pointer"><u>Status</u></th>
            </a>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ todo_list_item.name }}</td>
            <td>{{ todo_list_item.create_date | date:'d M Y' }}</td>
            <td>{{ todo_list_item.deadline |date:'d M Y' }}</td>
            <td>{{ todo_list_item.status }}</td>
            </td>
        </tr><br>
        <tr>
            <td>{{ todo_list_item.description }}</td>
        </tr>
    </tbody>
</table>
<a id='button' class='button' href='/'>Home</a>
{% endblock content %}

templates/todo/index.html
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Todo List</title>
    {% load static %}
    <script src='https://code.jquery.com/jquery-3.3.1.min.js'></script>
    <link rel='stylesheet' href='{% static  'css/index.css' %}'>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css'>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js'></script>
</head>
<body>
    <div class='home-page'>
        <div class='login-info'>
            {% block content %}
                {% if user.is_authenticated %}
                    <p>
                    <h3> Hi {{ user.username }}! </h3>
                    <a href='/todo/logout' class='button'>Log Out</a></p>
                {% else %}
                    <h3>You are not logged in</h3>
                    <a href='/todo/login'>Log In</a>
                {% endif %}
            {% endblock %}
        </div>
        <div class='todolist'>
            {% include 'todo/list.html' %}
        </div>
    </div>
</body>
</html>

templates/todo/list.html
{% if list and not todo_list_items %}
    <div class='container col-md-12'>
        <h3>{{ user.username }}'s ToDoLists</h3>
        <div class='section col-md-6'>
            {% for todo in list %}
                <ul>
                    <li><b>Name: {{ todo.name }} | Created Date: {{ todo.create_date | date:'d M Y' }}</b></li>
                    | <a href='{% url 'update_todo_list' todo.id %}'>Update</a>
                    | <a href='{% url 'delete_todo_list' todo.id %}'>Delete</a>
                    | <a href='{% url 'todo_list_items' todo.id %}'>Items</a>
                    | <a href='{% url 'create_todo_list_item' todo.id %}'>Add Item</a>
                </ul>
            {% endfor %}
        </div>
        <div class='section col-md-6'>
            <a class='button' href='{% url 'create_todo_list' %}'>Create Todolist</a>
        </div>
    </div>
{% elif not todo_list_items and not list %}
    <div class='container col-md-12'>
        <div class='section col-md-6'>
            <a class='button' href='/'>Home</a>
            <a class='button' href='{% url 'create_todo_list' %}'>Create Todolist</a>
        </div>
    </div>
{% endif %}

{% if todo_list_items and not list %}
    <div class='container col-md-12'>
    <h3><u>{{ todo_list.name }} Items </u></h3>
    <select id='statusFilter' onchange='myFunction()' class='form-control' placeholder='Select'>
        <option>ALL</option>
        <option>UNCOMPLETED</option>
        <option>COMPLETED</option>
        <option>EXPIRED</option>
    </select>
    <table class='item-table col-md-12' id='myTable'>
        <thead>
        <tr>
            <th><a style="cursor: pointer">Name</a>
                <input type='text' id='myInput' onkeyup='searchFunction()' placeholder='Search for names..'
                       title='Type in a name'>
            </th>
            <th><a style="cursor: pointer"><u>Created Date</u></th>
            </a>
            <th><a style="cursor: pointer"><u>Deadline</u></th>
            </a>
            <th><a style="cursor: pointer"><u>Status</u></th>
            </a>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in todo_list_items %}
            <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.create_date | date:'d M Y' }}</td>
            <td>{{ item.deadline |date:'d M Y' }}</td>
            <td>{{ item.status }}</td>
            <td><a href='{% url 'update_todo_list_item' item.id %}'>Update</a> <br>
                <a href='{% url 'delete_todo_list_item' item.id %}'>Delete</a><br>
                <a href='{% url 'mark_todo_list_item' item.id %}'>
                    {% if item.status == 'COMPLETED' %}
                        Mark as Uncompleted
                    {% elif item.status == 'UNCOMPLETED' %}
                        Mark as Completed
                    {% endif %}
                </a><br>
                <a href='{% url 'detail' item.id %}'>Details</a>
            </td>
        {% endfor %}
        </tr>
        </tbody>
    </table>

    <a id='createButton' class='button' href='{% url 'create_todo_list_item' todo_list.id %}'>Create Todolist Item</a>
    <a id='createButton' class='button' href='/'>Home</a>
{% endif %}
</div>
<script>
    function searchFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById('myInput');
        filter = input.value.toUpperCase();
        table = document.getElementById('myTable');
        tr = table.getElementsByTagName('tr');
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName('td')[0];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = '';
                } else {
                    tr[i].style.display = 'none';
                }
            }
        }
    }
</script>

<script>
    function myFunction() {
        var input, filter, table, tr, td, i;
        input = document.getElementById('statusFilter');
        filter = input.value.toUpperCase();
        table = document.getElementById('myTable');
        tr = table.getElementsByTagName('tr');

        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName('td')[3];
            if (td) {
                if (td.innerHTML.toUpperCase() == (filter) || (filter == 'ALL')) {
                    tr[i].style.display = '';
                } else {
                    tr[i].style.display = 'none';
                }
            }
        }
    }

    const table = document.getElementById('myTable');
    const headers = table.querySelectorAll('th');
    [].forEach.call(headers, function (header, index) {
        header.addEventListener('click', function () {
            sortColumn(index);
        });
    });
    const tableBody = table.querySelector('tbody');
    const rows = tableBody.querySelectorAll('tr');
    const sortColumn = function (index) {
        const direction = directions[index] || 'asc';
        const multiplier = (direction === 'asc') ? 1 : -1;
        const newRows = Array.from(rows);
        newRows.sort(function (rowA, rowB) {
            const cellA = rowA.querySelectorAll('td')[index].innerHTML;
            const cellB = rowB.querySelectorAll('td')[index].innerHTML;
            const a = transform(index, cellA);
            const b = transform(index, cellB);

            switch (true) {
                case a > b:
                    return 1 * multiplier;
                case a < b:
                    return -1 * multiplier;
                case a === b:
                    return 0;
            }
        });
        directions[index] = direction === 'asc' ? 'desc' : 'asc';
        [].forEach.call(rows, function (row) {
            tableBody.removeChild(row);
        });
        newRows.forEach(function (newRow) {
            tableBody.appendChild(newRow);
        });
    };
    const directions = Array.from(headers).map(function (header) {
        return '';
    });
    const transform = function(index, content) {
    const type = headers[index].getAttribute('data-type');
    switch (type) {
        case 'number':
            return parseFloat(content);
        case 'string':
        default:
            return content;
    }
};
</script>

templates/todo/update_list.html
{% extends 'todo/index.html' %}
{% block content %}
    <form method='post'>
        <h3> Update ToDoList </h3>
        {% csrf_token %}
        {{ update_todo_list }}
        <button type='submit'>Update</button>
    </form>
{% endblock content %}

templates/todo/update_list_item.html
{% extends 'todo/index.html' %}
{% block content %}
    <form method='post'>
        <h3> Update ToDoList Item</h3>
        {% csrf_token %}
        {% for item in update_todo_list_item %} <br>
            <label for='post'> {{ item }} </label>
        {% endfor %}
        <button type='submit'>Update</button>
    </form>
    <script>
        $('#id_deadline').before('<span> Deadline : </span>')
    </script>
{% endblock content %}